name: SOFA Feed Sync and Cloudflare Deployment

on:
  workflow_dispatch:
  schedule:
    # Run every 12 hours to sync and deploy
    - cron: '0 */12 * * *'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize empty files for first deployment
      run: |
        chmod +x init-empty-files.sh
        ./init-empty-files.sh

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetch upstream SOFA feeds with validation
      run: |
        # Function to fetch and validate JSON
        fetch_json() {
          local url=$1
          local output=$2
          
          # Create directory if it doesn't exist
          mkdir -p $(dirname "$output")
          
          # Fetch with proper headers
          if curl -H "Accept: application/json" -sS "$url" -o "$output.tmp"; then
            # Check if it's valid JSON
            if jq . "$output.tmp" > /dev/null 2>&1; then
              mv "$output.tmp" "$output"
              echo "✓ Successfully fetched and validated $output"
            else
              echo "✗ Invalid JSON from $url - using empty JSON"
              if [[ "$output" == *"_data_feed.json" ]]; then
                echo "[]" > "$output"
              else
                echo "{}" > "$output"
              fi
              rm -f "$output.tmp"
            fi
          else
            echo "✗ Failed to fetch $url - using empty JSON"
            if [[ "$output" == *"_data_feed.json" ]]; then
              echo "[]" > "$output"
            else
              echo "{}" > "$output"
            fi
          fi
        }
        
        # Fetch production feeds from sofa.macadmins.io
        fetch_json "https://sofafeed.macadmins.io/v1/macos_data_feed.json" "v1/macos_data_feed.json"
        fetch_json "https://sofafeed.macadmins.io/v1/ios_data_feed.json" "v1/ios_data_feed.json"
        fetch_json "https://sofafeed.macadmins.io/v1/timestamp.json" "v1/timestamp.json"
        
        # Fetch RSS separately as it's XML
        curl -sS "https://sofafeed.macadmins.io/v1/rss_feed.xml" -o "v1/rss_feed.xml" || echo "Failed to fetch RSS"
        
        # Create proper empty cache files needed by Vue components
        # cve_details.json needs specific structure
        echo '{"CVE_Details": []}' > cache/cve_details.json
        
        # essential_links.json needs specific structure
        echo '{}' > cache/essential_links.json
        
        # supported_devices.json needs specific structure
        echo '{}' > cache/supported_devices.json
        
        # Copy to public directory for VitePress
        cp v1/*.json public/v1/
        cp v1/*.xml public/v1/

    - name: Build VitePress site
      run: npm run docs:build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: sofa-feed  # Change this to your project name
        directory: web/.vitepress/dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        wranglerVersion: '3'

    - name: Commit feed updates (if changed)
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add v1/* cache/* || true
        git commit -m "Sync upstream SOFA feeds - $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push