name: macOS and iOS SOFA Scan (Modified for Cloudflare)

on:
  workflow_dispatch:  # Only manual trigger since we're using upstream sync

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . -t sofa_scan

    - name: Run Docker container with macOS and iOS arguments
      run: |
        docker run --name sofa_scan_container \
          -e TIMESTAMP_FILE_PATH=/app/v1/timestamp.json \
          -v $(pwd)/v1:/app/v1 sofa_scan macOS iOS

    - name: Copy resulting JSON files from container to host
      run: |
        docker cp sofa_scan_container:/app/v1/timestamp.json v1/. || echo "Failed to copy timestamp.json"
        docker cp sofa_scan_container:/app/macos_data_feed.json v1/. || true
        docker cp sofa_scan_container:/app/ios_data_feed.json v1/. || true
        docker cp sofa_scan_container:/app/rss_feed.xml v1/. || true
        docker cp sofa_scan_container:/app/cache . || echo "Failed to copy cache files"
        docker cp sofa_scan_container:/app/time-series.csv .

    - name: List contents of v1
      run: ls -la v1/

    - name: Copy v1 data feed files into public dir for VitePress
      run: |
        mkdir -p public/v1
        cp -r v1/*.json public/v1/
        cp -r v1/*.xml public/v1/

    - name: Commit and push if changes are detected
      run: |
        timestamp=$(date +'%Y-%m-%d %H:%M:%S')
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add v1/*.json v1/*.xml cache/*.json time-series.csv
        git add public/v1/*.json public/v1/*.xml
        git commit -m "Update SOFA data - $timestamp" -a || exit 0
        git push

    # Removed: Un prettify jsons (lines 58-68)
    # Removed: S3cmd setup (lines 70-76)
    # Removed: Create gzipped jsons (lines 78-82)
    # Removed: Upload to Digital Ocean Beta (lines 84-91)
    # Removed: Upload to Digital Ocean Production (lines 93-101)