name: Run MUF Scan

on:
  # Allows manual triggering of the workflow from the GitHub UI or through the API
  workflow_dispatch:
  
  # Defines scheduled triggers for the workflow
  schedule:
    # Monday, Tuesday, Thursday, and Friday every 1 hour from 5:00 PM to 8:00 PM CET
    - cron: '0 17-20 * * 1,2,3,4,5'
    
    # On every day every 4 hours
    - cron: '30 */4 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build . -t muf_scan
      
    - name: Run Docker container
      run: docker run --name muf_scan_container -e OS_VERSIONS="Sonoma 14, Ventura 13, Monterey 12, iOS 17, iOS 16" muf_scan
      
    - name: Copy resulting JSON files from container to host
      run: |
        docker cp muf_scan_container:/app/macos_monterey_12.json .
        docker cp muf_scan_container:/app/macos_sonoma_14.json .
        docker cp muf_scan_container:/app/macos_ventura_13.json .
        docker cp muf_scan_container:/app/ios_16.json .
        docker cp muf_scan_container:/app/ios_17.json .
        docker cp muf_scan_container:/app/time-series.csv .
      
    - name: Commit and push if changes are detected
      run: |
        timestamp=$(date +'%Y-%m-%d %H:%M:%S')
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add *.json time-series.csv
        git commit -m "Update MUF data - $timestamp" -a || exit 0  # Commit all changes, otherwise exit gracefully
        git push
