name: Run MUF Scan

on:
  workflow_dispatch:
    schedule:
      # Monday, Tuesday, Thursday, and Friday every 1 hour from 5:00 PM to 8:00 PM CET
      - cron: '0 17-20 * * 1,2,4,5'
      # On weekdays except Friday every 4 hours from 12:00 AM to 4:00 PM and from 9:00 PM to 11:59 PM CET
      - cron: '0 0-16/4,21-23/4 * * 1-4'
      # On weekends every 12 hours from 12:00 AM to 11:59 PM CET
      - cron: '0 */12 * * 6-7'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build . -t muf_scan
      
    - name: Run Docker container
      run: docker run --name muf_scan_container -e MACOS_VERSIONS="Monterey 12, Sonoma 14, Ventura 13" muf_scan
      
    - name: Copy resulting JSON files from container to host
      run: |
        docker cp muf_scan_container:/app/muf_data_monterey_12.json .
        docker cp muf_scan_container:/app/muf_data_sonoma_14.json .
        docker cp muf_scan_container:/app/muf_data_ventura_13.json .
      
    - name: Commit and push if changes are detected
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add muf_data_*.json
        git commit -m "Update MUF data" -a || exit 0   # Commit if there are changes, otherwise exit gracefully
        git push
